// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0ImeAbAEtKXwBxRt2EBX5B1Gb1l34nPw',
    appId: '1:932549972431:web:4ffebd4be266e7f5c302ba',
    messagingSenderId: '932549972431',
    projectId: 'event-2046f',
    authDomain: 'event-2046f.firebaseapp.com',
    storageBucket: 'event-2046f.firebasestorage.app',
    measurementId: 'G-DYPRX1NHNL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGV8fCdeip-s6JQe4zDVJQi1a0OfImz84',
    appId: '1:932549972431:android:5249af5a4b4ee737c302ba',
    messagingSenderId: '932549972431',
    projectId: 'event-2046f',
    storageBucket: 'event-2046f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3p7fdiMt1RoDI1gjYuNJtlx_Yof1H9WQ',
    appId: '1:932549972431:ios:ec63777d6342bfbbc302ba',
    messagingSenderId: '932549972431',
    projectId: 'event-2046f',
    storageBucket: 'event-2046f.firebasestorage.app',
    iosBundleId: 'com.example.eventManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3p7fdiMt1RoDI1gjYuNJtlx_Yof1H9WQ',
    appId: '1:932549972431:ios:ec63777d6342bfbbc302ba',
    messagingSenderId: '932549972431',
    projectId: 'event-2046f',
    storageBucket: 'event-2046f.firebasestorage.app',
    iosBundleId: 'com.example.eventManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0ImeAbAEtKXwBxRt2EBX5B1Gb1l34nPw',
    appId: '1:932549972431:web:ad3ae0801012e3a1c302ba',
    messagingSenderId: '932549972431',
    projectId: 'event-2046f',
    authDomain: 'event-2046f.firebaseapp.com',
    storageBucket: 'event-2046f.firebasestorage.app',
    measurementId: 'G-H32N45GSHQ',
  );
}
